apiVersion: v1
kind: Pod
metadata:
  namespace: {{cookiecutter.namespace}}
  name: airflow-task
  labels:
    app.kubernetes.io/name: airflow
spec:
  nodeSelector:
        "purpose": {{cookiecutter._nodeSelectorPurposeWorker}}
  tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "{{cookiecutter._nodeSelectorPurposeWorker}}"
    effect: "NoSchedule"   
  containers:
    - args: []
      command: []
      env:
      image: dummy-image
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/opt/airflow/logs"
          name: airflow-logs
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory:  256Mi
          cpu: 200m
      name: base
  securityContext:
    runAsUser: 50000
    fsGroup: 50000
  hostNetwork: false
  restartPolicy: Never
  volumes:
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: airflow-logs-pvc
