apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc-webserver
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc-scheduler
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc-worker
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
