apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{cookiecutter.namespace}}
  name: scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      nodeSelector:
        "purpose": "webserver"
      tolerations:
      - key: "purpose"
        operator: "Equal"
        value: "webserver"
        effect: "NoSchedule"   
      initContainers:
      - name: nfs-permission-fix
        image: alpine:latest
        command: ["/bin/sh", "-c","/bin/chown -R 50000:0 /opt/airflow/"]
        volumeMounts:
        - name: airflow-logs
          mountPath: "/opt/airflow/airflow_logs"
        {% if cookiecutter.nfs_dags!=None -%}
        - name: airflow-dags
          mountPath: "/opt/airflow/airflow_dags"
        {%- endif %}
      containers:
      - name: airflow-scheduler
        image: airflow-scheduler-worker
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["airflow db init; airflow users delete -u admin; airflow users create --role Admin --username admin --email admin --firstname admin --lastname admin --password $admin_pass; unset admin_pass; airflow scheduler"]
        resources:
{% if cookiecutter.airflow_performance == 'small' -%}
{% include "{{cookiecutter.yamles_folder_name}}/airflow_mode_config/small/scheduler.cfg" %}
{% elif cookiecutter.airflow_performance == 'standard' -%}
{% include "{{cookiecutter.yamles_folder_name}}/airflow_mode_config/standard/scheduler.cfg" %}
{% elif cookiecutter.airflow_performance == 'large' -%}
{% include "{{cookiecutter.yamles_folder_name}}/airflow_mode_config/large/scheduler.cfg" %}
{%- endif %}
        env:
        - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
          value: /opt/airflow/airflow_logs
        - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
          value: gcr.io/{{cookiecutter.project_id}}/airflow
        - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
          value: latest
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: {{cookiecutter.namespace}}
        {% if cookiecutter.nfs_dags!=None -%}
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /opt/airflow/airflow_dags
        {%- endif %}
        volumeMounts:
        - mountPath: /opt/airflow/airflow_logs
          name: airflow-logs
        {% if cookiecutter.nfs_dags!=None -%}
        - mountPath: /opt/airflow/airflow_dags
          name: airflow-dags
        {%- endif %}
        livenessProbe:
          exec:
            command:
            - python3
            - -Wignore
            - -c
            - |
              from airflow.jobs.scheduler_job import SchedulerJob
              from airflow.utils.net import get_hostname
              import sys
              job = SchedulerJob.most_recent_job()
              sys.exit(0 if job.is_alive() and job.hostname == get_hostname() else 1)
          failureThreshold: 3
          periodSeconds: 60
          timeoutSeconds: 5
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: nfs-pvc
        {% if cookiecutter.nfs_dags!=None -%}
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: nfs-pvc-dags
        {%- endif %}