apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: {{cookiecutter.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      nodeSelector:
        "purpose": "webserver"
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-disk
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir -p /exports/dags; mkdir -p /exports/logs"]
      volumes:
        - name: nfs-disk
          gcePersistentDisk:
            pdName: nfs-disk-{{cookiecutter.workspace}}-{{cookiecutter.env}}
            fsType: ext4

---

apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server