apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{cookiecutter.namespace}}
  name: webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec: 
      nodeSelector:
        "purpose": "webserver"
      containers:
      - name: airflow-webserver    
        image: airflow-webserver
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c","airflow webserver"]
        resources:
{% if cookiecutter.airflow_performance == 'small' -%}
{% include "{{cookiecutter.yamles_folder_name}}/airflow_mode_config/small/webserver.cfg" %}
{% elif cookiecutter.airflow_performance == 'standard' -%}
{% include "{{cookiecutter.yamles_folder_name}}/airflow_mode_config/standard/webserver.cfg" %}
{% elif cookiecutter.airflow_performance == 'large' -%}
{% include "{{cookiecutter.yamles_folder_name}}/airflow_mode_config/large/webserver.cfg" %}
{%- endif %}
        env:
        - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
          value: /opt/airflow/airflow_logs
        - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
          value: gcr.io/{{cookiecutter.project_id}}/airflow
        - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
          value: latest
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: {{cookiecutter.namespace}}
        volumeMounts:
          - mountPath: /opt/airflow/airflow_logs
            name: airflow-logs
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: nfs-pvc


