---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-map
  namespace: {{cookiecutter.namespace}}
data:
  redis-config: |
    maxmemory 50mb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{cookiecutter.namespace}}
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-redis
    spec:
      nodeSelector:
        "purpose": {{cookiecutter._nodeSelectorPurposeWebserver}}  
      containers:
      - name: airflow-redis
        image: redis:6.2.6-alpine
        command:
          - redis-server
          - "/config/redis.conf"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "10M"
            cpu: "0.08"
          limits:
            memory: "100M"
            cpu: "0.1"
        ports:
        - containerPort: 6379
                volumeMounts:
        - mountPath: /data
          name: airflow-redis
        - mountPath: /config
          name: airflow-redis-config
      volumes:
        - name: airflow-redis
        - name: airflow-redis-config
          configMap:
            name: redis-config-map
            items:
            - key: redis-config
              path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  namespace: {{cookiecutter.namespace}}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: airflow-redis