apiVersion: v1
kind: Service
metadata:
  namespace: {{cookiecutter.namespace}}
  name: airflow-webserver
spec:
  type: LoadBalancer
  selector:
    app: airflow-webserver
  ports:
  - name: http
    protocol: TCP
    port: 8080

