apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v1.10.0/cluster-operator.yml
  - airflow_log_pvc.yaml
  - airflow_service.yaml
  - pgbouncer.yaml
  - airflow_roles.yaml
  - airflow_secret.yaml
  - RabbitmqCluster.yaml
  - airflow_scheduler_deployment.yaml
  - airflow_worker_deployment.yaml
  - airflow_webserver_deployment.yaml