apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - airflow_nfsserver_deployment.yaml
  - airflow_service.yaml
  - pgbouncer.yaml
  - airflow_roles.yaml
  - airflow_secret.yaml
  - airflow_redis_deployment.yaml
  - airflow_nfs_pvc.yaml
  - airflow_scheduler_deployment.yaml
  - airflow_worker_deployment.yaml
  - airflow_webserver_deployment.yaml