apiVersion: v1
kind: Service
metadata:
  name: airflow-pgbouncer
  namespace: {{cookiecutter.namespace}}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pgbouncer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgbouncer
  namespace: {{cookiecutter.namespace}}
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      nodeSelector:
        "purpose": {{cookiecutter._nodeSelectorPurposeWebserver}}
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name:  postgres-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name:  postgres-config
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name:  postgres-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name:  postgres-config
        - name: POOL_MODE
          value: transaction
        - name: SERVER_RESET_QUERY
          value: DISCARD ALL
        image: edoburu/pgbouncer:1.9.0
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - killall -INT pgbouncer && sleep 120
        name: pgbouncer
        ports:
        - containerPort: 5432
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all


