apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: {{cookiecutter.namespace}}
  labels:
    app: celery
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            nodeSelector:
              "purpose": {{cookiecutter._nodeSelectorPurposeAdditional}}
            containers: []
            securityContext: {}
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "3.7Gi"
      cpu: "1.5"
  rabbitmq:
          additionalConfig: |
                  default_user = admin 
                  default_pass = admin
                  default_user_tags.administrator = true
