apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: airee
  namespace: flux-system
spec:
  image: gcr.io/{{cookiecutter.project_id}}/{{cookiecutter.workspace}}-{{cookiecutter.env}}
  interval: 1m0s
  secretRef:
    name: gcr-credentials