---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: airee
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./{{cookiecutter.yamles_folder_name}}
  prune: true
  sourceRef:
    kind: GitRepository
    name: airee
  targetNamespace: {{cookiecutter.namespace}}