apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: airee
  namespace: flux-system
spec:
  image: gcr.io/dsstream-airflowk8s/{{cookiecutter.workspace}}
  interval: 1m0s
  secretRef:
    name: gcr-credentials