apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: airee
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: airee
  interval: 1m
  update:
    strategy: Setters
    path: ./yamles
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: fluxbot@dsstream.com
      messageTemplate: |
        An automated update from FluxBot
        [ci skip]        
    push:
      branch: main