---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: airee
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/DsAirKube/{{cookiecutter.workspace}}_app_{{cookiecutter.env}}.git