name: Build image webserver
on: push

jobs:
  rebuild_image_webserver:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Authorization
      run: docker login -u _json_key --password-stdin https://gcr.io < ${GOOGLE_APPLICATION_CREDENTIALS}
    - name: Get project id
      run: echo "PROJECT_ID=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 2 | sed 's/_.*//' )" >> $GITHUB_ENV; echo "TIMESTAMP_IMAGES=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV;
    - name: Docker build
      run: docker build . -t gcr.io/{{cookiecutter.project_id}}/airflow:web-${TIMESTAMP_IMAGES}00Z
    - name: Docker push
      run: docker push gcr.io/{{cookiecutter.project_id}}/airflow:web-${TIMESTAMP_IMAGES}00Z