name: Build image worker
on:
  push:
    paths:
      - 'app/**'

jobs:
  rebuild_image_worker:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Authorization
      run: docker login -u _json_key --password-stdin https://gcr.io < ${GOOGLE_APPLICATION_CREDENTIALS}
    - name: Get timestamp
      run: echo "TIMESTAMP_IMAGES=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV;
    - name: Clone workspace repo
      run: rm -rf dags; git clone https://oauth2:${PAT_TOKEN}@github.com/DsAirKube/{{cookiecutter.workspace}}_workspace_data_dev.git dags
    - name: Move dags
      run: rm -rf app/dags 2>/dev/null; mv dags/dags app/.
    - name: Docker build
      run: docker build . -t gcr.io/{{cookiecutter.project_id}}/{{cookiecutter.workspace}}:worker-${TIMESTAMP_IMAGES}00Z
    - name: Docker push
      run: docker push gcr.io/{{cookiecutter.project_id}}/{{cookiecutter.workspace}}:worker-${TIMESTAMP_IMAGES}00Z