name: Deploy airflow pods
on: push

env:
  GCP_PROJECT: "{{cookiecutter.project_id}}"
  CLUSTER_NAME: "{{cookiecutter.cluster_name}}"
  REGION: "{{cookiecutter.region}}"

jobs:
  initialization:
    runs-on: self-hosted
    steps:
    - name: authorize gcp
      run: gcloud auth activate-service-account ${GOOGLE_IMPERSONATE_SERVICE_ACCOUNT} --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
    - name: set default project
      run: gcloud config set project ${GCP_PROJECT}
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: check kubernetes connection
      run: gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${REGION} --project ${GCP_PROJECT}
    - name: deploy airee objects
      run: sh gcp_main.sh
    - name: check webserver ip
      run: kubectl get service airflow-webserver -n airflow
    - name: check webserver ip
      run: sleep 60 && kubectl get service airflow-webserver -n airflow
      env: 
        TF_VAR_github_token: {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}
