kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_nfsserver_deployment.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_service.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/pgbouncer.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_roles.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_redis_deployment.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_nfs_pvc.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_scheduler_deployment.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_worker_deployment.yaml
kubectl apply -f ./{{cookiecutter.yamles_folder_name}}/airflow_webserver_deployment.yaml